### ISSUE TITLE
Process required: Create Procfile

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/My-first-Agile-Project#10]
**Process:**
- [ ] Create Procfile for Heroku

 **Benefit:**
 Allows the application to run in Heroku

### Tasks 

- [ ] Install dependencies for the project to run
- [ ] Tell Heroku what language we're using, in our case it's 'Python'
