### ISSUE TITLE
Process required: Deploy using GitHub

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/My-first-Agile-Project#11]
**Process**
Connect GitHub account for final deployment stages 

**Benefit**
Allow deployment to production

## Tasks
- [ ] Connect your GitHub account from the deployment method of settings on your Heroku app
- [ ] Select the correct repository and click connect
- [ ] Enable Automatic deploys from the main branch
- [ ] Click deploy branch
