### ISSUE TITLE
Process required: Cloudinary Setup

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/My-first-Agile-Project#13]
**Process**
Create a Cloudinary account so that 

**Benefit**
I can store my media files

### Tasks:
- [ ]  Visit the Cloudinary website
- [ ]  Click on the Sign Up For Free button
- [ ]  Provide name, email address and choose a password
- [ ] Choose Programmable Media for image and video API
   - [ ]  Edit the assigned cloud name to something more memorable
- [ ] Click Create Account
- [ ] Verify your email and you will be brought to the dashboard
