### ISSUE TITLE
Process required: Create Heroku app

### ISSUE THREAD

**Issue by chris-townsend** [chris-townsend/My-first-Agile-Project#8]
**Process:**
Create an account with Heroku to process setting up the app

**Benefit:**
Allow deployment on Heroku

## Tasks

- [ ] Create Heroku account
- [ ] Make primary development language 'Python'
- [ ] Validate confirmation email 
- [ ] Set password

#### 
- [ ] Create a new App with a meaningful name and choose region
